### ISSUE TITLE
[rsa-export] pinging 

### ISSUE THREAD

**Issue by Geobert** [smallglitch/tranquility#2]
Hi,

Sorry to create an issue unrelated to the project, but maybe you don't get notification from GitLab so I'm trying here to get your attention :)  I've created a question on `rsa-export`  and I don't know if you have seen it: https://gitlab.com/smallglitch/rsa-export/-/issues/3

Regards,

**Comment by smallglitch** [comment]
No problem, I've reponded to your issue on GitLab (https://gitlab.com/smallglitch/rsa-export/-/issues/3#note_449166541)

**Comment by Geobert** [comment]
Sorry to ping you here again, but I think I found a quite serious issue in rsa-export 0.2.1 :)
